class Flower:
    def __init__(self, type, nectar, pollen, energy_cost):
        self.type = type
        self.nectar = nectar
        self.pollen = pollen
        self.energy_cost = energy_cost


flowers = [
    Flower(type="rose", nectar=10, pollen=15, energy_cost=5),
    Flower(type="honeysuckle", nectar=20, pollen=10, energy_cost=8),
    Flower(type="sunflower", nectar=15, pollen=15, energy_cost=10),
    Flower(type="daisy", nectar=10, pollen=10, energy_cost=4),
    Flower(type="orchid", nectar=5, pollen=5, energy_cost=2),
    Flower(type="rose", nectar=12, pollen=14, energy_cost=6),
    Flower(type="sunflower", nectar=16, pollen=14, energy_cost=9),
    Flower(type="daisy", nectar=9, pollen=11, energy_cost=5),
    Flower(type="honeysuckle", nectar=18, pollen=12, energy_cost=7),
    Flower(type="orchid", nectar=6, pollen=4, energy_cost=3),
    Flower(type="rose", nectar=11, pollen=13, energy_cost=7),
    Flower(type="honeysuckle", nectar=21, pollen=9, energy_cost=9),
    Flower(type="sunflower", nectar=14, pollen=16, energy_cost=8),
    Flower(type="daisy", nectar=11, pollen=9, energy_cost=4),
    Flower(type="orchid", nectar=4, pollen=6, energy_cost=2),
    Flower(type="rose", nectar=13, pollen=12, energy_cost=5),
    Flower(type="honeysuckle", nectar=19, pollen=11, energy_cost=8),
    Flower(type="sunflower", nectar=15, pollen=14, energy_cost=11),
    Flower(type="daisy", nectar=8, pollen=12, energy_cost=5),
    Flower(type="orchid", nectar=7, pollen=3, energy_cost=3),
    Flower(type="tulip", nectar=8, pollen=7, energy_cost=3),
    Flower(type="lilac", nectar=12, pollen=9, energy_cost=4),
    Flower(type="marigold", nectar=14, pollen=13, energy_cost=6),
    Flower(type="lavender", nectar=5, pollen=8, energy_cost=2),
    Flower(type="poppy", nectar=7, pollen=6, energy_cost=5),
    Flower(type="lily", nectar=13, pollen=10, energy_cost=4),
    Flower(type="violet", nectar=4, pollen=5, energy_cost=1),
    Flower(type="snapdragon", nectar=6, pollen=7, energy_cost=3),
    Flower(type="chrysanthemum", nectar=9, pollen=8, energy_cost=4),
    Flower(type="iris", nectar=5, pollen=7, energy_cost=3),
    Flower(type="tulip", nectar=9, pollen=6, energy_cost=4),
    Flower(type="lilac", nectar=11, pollen=10, energy_cost=5),
    Flower(type="marigold", nectar=15, pollen=14, energy_cost=7),
    Flower(type="lavender", nectar=6, pollen=9, energy_cost=3),
    Flower(type="poppy", nectar=8, pollen=5, energy_cost=4),
    Flower(type="lily", nectar=12, pollen=11, energy_cost=5),
    Flower(type="violet", nectar=5, pollen=4, energy_cost=2),
    Flower(type="snapdragon", nectar=7, pollen=8, energy_cost=4),
    Flower(type="chrysanthemum", nectar=8, pollen=9, energy_cost=5),
    Flower(type="iris", nectar=6, pollen=8, energy_cost=4),
    Flower(type="tulip", nectar=7, pollen=8, energy_cost=3),
    Flower(type="lilac", nectar=13, pollen=11, energy_cost=5),
    Flower(type="marigold", nectar=16, pollen=12, energy_cost=6),
    Flower(type="lavender", nectar=4, pollen=7, energy_cost=2),
    Flower(type="poppy", nectar=9, pollen=7, energy_cost=6),
    Flower(type="lily", nectar=11, pollen=12, energy_cost=6),
    Flower(type="violet", nectar=3, pollen=6, energy_cost=1),
    Flower(type="snapdragon", nectar=8, pollen=6, energy_cost=3),
    Flower(type="chrysanthemum", nectar=10, pollen=7, energy_cost=5),
    Flower(type="iris", nectar=7, pollen=9, energy_cost=4),
    Flower(type="magnolia", nectar=12, pollen=8, energy_cost=5),
    Flower(type="geranium", nectar=9, pollen=10, energy_cost=4),
    Flower(type="begonia", nectar=8, pollen=6, energy_cost=3),
    Flower(type="peon", nectar=7, pollen=7, energy_cost=2),
    Flower(type="fuchsia", nectar=5, pollen=5, energy_cost=2),
    Flower(type="carnation", nectar=11, pollen=9, energy_cost=6),
    Flower(type="anemone", nectar=6, pollen=4, energy_cost=3),
    Flower(type="azalea", nectar=4, pollen=6, energy_cost=2),
    Flower(type="buttercup", nectar=8, pollen=5, energy_cost=3),
    Flower(type="camellia", nectar=10, pollen=7, energy_cost=4),
    Flower(type="cosmos", nectar=9, pollen=8, energy_cost=3),
    Flower(type="daffodil", nectar=7, pollen=9, energy_cost=4),
    Flower(type="magnolia", nectar=13, pollen=7, energy_cost=4),
    Flower(type="geranium", nectar=10, pollen=11, energy_cost=5),
    Flower(type="begonia", nectar=9, pollen=5, energy_cost=4),
    Flower(type="peon", nectar=8, pollen=8, energy_cost=3),
    Flower(type="fuchsia", nectar=6, pollen=6, energy_cost=3),
    Flower(type="carnation", nectar=12, pollen=8, energy_cost=7),
    Flower(type="anemone", nectar=7, pollen=5, energy_cost=4),
    Flower(type="azalea", nectar=5, pollen=7, energy_cost=3),
    Flower(type="buttercup", nectar=9, pollen=6, energy_cost=4),
    Flower(type="camellia", nectar=11, pollen=8, energy_cost=5),
    Flower(type="cosmos", nectar=10, pollen=7, energy_cost=4),
    Flower(type="daffodil", nectar=8, pollen=10, energy_cost=5),
    Flower(type="magnolia", nectar=14, pollen=9, energy_cost=6),
    Flower(type="geranium", nectar=8, pollen=9, energy_cost=3),
    Flower(type="begonia", nectar=7, pollen=7, energy_cost=2),
    Flower(type="peon", nectar=6, pollen=6, energy_cost=2),
    Flower(type="fuchsia", nectar=4, pollen=4, energy_cost=1),
    Flower(type="carnation", nectar=13, pollen=10, energy_cost=8),
    Flower(type="anemone", nectar=5, pollen=3, energy_cost=2),
    Flower(type="azalea", nectar=3, pollen=5, energy_cost=1),
    Flower(type="buttercup", nectar=7, pollen=4, energy_cost=2),
    Flower(type="camellia", nectar=12, pollen=6, energy_cost=4),
    Flower(type="cosmos", nectar=11, pollen=9, energy_cost=5),
    Flower(type="daffodil", nectar=9, pollen=11, energy_cost=6),
    Flower(type="magnolia", nectar=11, pollen=10, energy_cost=7),
    Flower(type="geranium", nectar=11, pollen=12, energy_cost=6),
    Flower(type="begonia", nectar=10, pollen=8, energy_cost=5),
    Flower(type="peon", nectar=9, pollen=9, energy_cost=4),
    Flower(type="fuchsia", nectar=7, pollen=8, energy_cost=4),
    Flower(type="carnation", nectar=10, pollen=11, energy_cost=7),
    Flower(type="anemone", nectar=8, pollen=6, energy_cost=3),
    Flower(type="azalea", nectar=6, pollen=8, energy_cost=3),
    Flower(type="buttercup", nectar=10, pollen=7, energy_cost=5),
    Flower(type="camellia", nectar=13, pollen=9, energy_cost=6),
    Flower(type="cosmos", nectar=12, pollen=10, energy_cost=6),
    Flower(type="daffodil", nectar=10, pollen=12, energy_cost=7)
]
